VERSION=0.0.1

all:
	docker build -t lorenmh/coen280-project:latest -t lorenmh/coen280-project:$(VERSION) .
no-cache:
	docker build --no-cache -t lorenmh/coen280-project:latest -t lorenmh/coen280-project:$(VERSION) .
